# Copyright IBM Corp. 2023, 2025
# SPDX-License-Identifier: MPL-2.0

name: "Slack Status Notification"
author: Release Engineering <rel-eng@hashicorp.com>
description: Slack Status Notification (replacement for circleci_slack_status orb).

inputs:
  status:
    description: Pass through the GH conclusion/result value (success, failure, cancelled, or skipped)
    required: true
  slack-webhook-url:
    description: Slack application webhook URL to post the message (if unsure, ask RelEng to create one)
    required: true
  success-message:
    description: The message (in Markdown) to be sent when status is 'success'. If unset, no message will be sent
    default: ''
  failure-message:
    description: The message (in Markdown) to be sent when status is 'failure'. f unset, no message will be sent
    default: ''
  cancelled-message:
    description: The message (in Markdown) to be sent when status is 'cancelled'. If unset, no message will be sent
    default: ''
  skipped-message:
    description: The message (in Markdown) to be sent when status is 'skipped'. If unset, no message will be sent
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: this
      env:
        INPUT_STATUS: ${{inputs.status}}
        INPUT_SUCCESS-MESSAGE: ${{inputs.success-message}}
        INPUT_FAILURE-MESSAGE: ${{inputs.failure-message}}
        INPUT_CANCELLED-MESSAGE: ${{inputs.cancelled-message}}
        INPUT_SKIPPED-MESSAGE: ${{inputs.skipped-message}}
      with:
        # github-token: uncomment-this-line-for-local-act-testing
        script: |
          return require(process.env.GITHUB_ACTION_PATH + '/main.js')({context, core})
    - name: Send Status
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      if: ${{ steps.this.outputs.result != '' }}
      with:
        webhook: ${{ inputs.slack-webhook-url }}
        webhook-type: incoming-webhook
        payload: ${{ steps.this.outputs.result }}

