# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: test action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-success-handling:
    runs-on: ubuntu-latest
    steps:
     # For testing, we must check ourselves out.
     - name: Checkout
       uses: actions/checkout@v2
     - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
       id: this
       with:
         debug: true
         script: |
           core.debug("test")
