# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: test action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-skip-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.0.0
      - if: ${{ 'false' != 'false' }}
        id: demo
        run: |
          exit 0
      - uses: ./
        if: ${{always()}}
        with:
          skipped-message: ":testing: A successful skipped message."
          status: ${{steps.demo.conclusion}}
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
  test-always-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.0.0
      - id: demo
        continue-on-error: true
        run: |
          exit 1
      - uses: ./
        if: ${{always()}}
        with:
          failure-message: ":testing: A successful failure message."
          status: ${{steps.demo.outcome}}
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}

  test-missing-message-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.0.0
      - uses: ./
        with:
          status: success
          # Yes, success-message is undefined, this will emit no slack message!
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}

  test-success-message-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.0.0
      - uses: ./
        with:
          status: success
          success-message: ":testing: A successful success message."
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}

  test-cancelled-message-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.0.0
      - uses: ./
        with:
          status: cancelled
          cancelled-message: ":testing: A successful cancelled message."
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
