# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: test action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-skip-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@v2
      - if: ${{ 'false' != 'false' }}
        id: demo
        run: |
          exit 0
      - uses: ./
        if: ${{always()}}
        with:
          skipped-message: ":skip: A successfully skipped cmd message."
          status: ${{steps.demo.conclusion}}
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
  test-always-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@v2
      - id: demo
        run: |
          exit 0
      - uses: ./
        if: ${{always()}}
        with:
          failure-message: ":tada: A successful failure message."
          status: ${{job.status}}
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
  test-true-handling:
    runs-on: ubuntu-latest
    steps:
     # For testing, we must check ourselves out.
     - name: Checkout
       uses: actions/checkout@v2
     - uses: ./
       with:
          success-message: ":tada: A success message."
          status: true
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
  test-false-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          failure-message: ":tada: A (successful) failure message."
          status: false
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
  test-missing-message-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          was-successful: true # Yes, true, success-message is undefined
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
