# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: test action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-skip-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@v2
      - if: ${{ 'false' != 'false' }}
        id: demo
        run: |
          exit 0
      - uses: ./
        if: ${{always()}}
        with:
          skipped-message: ":skip: A successfully skipped cmd message."
          status: ${{steps.demo.conclusion}}
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
  test-always-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@v2
      - id: demo
        continue-on-error: true
        run: |
          exit 1
      - uses: ./
        if: ${{always()}}
        with:
          failure-message: ":tada: A successful failure message."
          status: ${{steps.demo.outcome}}
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}

  test-missing-message-handling:
    runs-on: ubuntu-latest
    steps:
      # For testing, we must check ourselves out.
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          status: success
          # Yes, success-message is undefined
          slack-webhook-url: ${{secrets.slack_webhook_url_feed_releng_test}}
