# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: test action
on:
  push:

jobs:
  test-success-handling:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          success-message: ":hooray: Yes."
          failure-message: ":boo: Nope."
          was-successful: true
          slack-webhook-url: https://www.example.com
  test-failure-handling:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          success-message: ":hooray: Yes."
          failure-message: ":boo: Nope."
          was-successful: false
          slack-webhook-url: https://www.example.com
